name: elegant_notification
description: A new flutter package to display notifications on top of the screen, full customizable with built-in themes
version: 1.0.0
homepage: https://github.com/koukibadr/Elegant-Notification

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/icons/error.png
    - assets/icons/info.png
    - assets/icons/success.png