on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
      - name: Install dependencies
        run: flutter pub get
      
      - name: Running Flutter analysis on package code
        run: flutter analyze
      
      - name: Runing widget testing
        run: dart pub publish --dry-run
      
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
